apiVersion: apps/v1

kind: Deployment

metadata:
  name: backend-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: teachua
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: teachua
        tier: backend
        track: stable
    spec:
      containers:
      - name: teachuaback
        image: registry646.azurecr.io/backend:1.5
        ports:
        - containerPort: 8080
        env:
        - name: DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: DATASOURCE_URL
        - name: DATASOURCE_USER
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: DATASOURCE_USER
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: DATASOURCE_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: JWT_SECRET
        - name: MY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: MY_PASSWORD
---
apiVersion: v1

kind: Service

metadata:
  name: teachua
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: teachua-demo3-new
spec:
  selector:
    app: teachua
    tier: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
