apiVersion: v1
kind: Secret
metadata:
  name: back-secret
type: Opaque
stringData:
  DATASOURCE_URL: jdbc:postgresql://postgres-base.postgres.database.azure.com:5432/teachua?user=demo3@postgres-base&password=p@ssw0rd&sslmode=require
  DATASOURCE_USER: demo3
  DATASOURCE_PASSWORD: p@ssw0rd
  JWT_SECRET: "SecretString"
  MY_PASSWORD: "Application is running"
