FROM tomcat:9.0.54-jdk11-openjdk

COPY dev.war /usr/local/tomcat/webapps/

ENV DATASOURCE_URL $DATASOURCE_URL
ENV DATASOURCE_USER $DATASOURCE_USER
ENV DATASOURCE_PASSWORD $DATASOURCE_PASSWORD
ENV MY_PASSWORD $MY_PASSWORD
ENV JWT_SECRET $JWT_SECRET
