apiVersion: apps/v1

kind: Deployment

metadata:
  name: frontend-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: teachua
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: teachua
        tier: frontend
        track: stable
    spec:
      containers:
      - name: teachuafront
        image: registry646.azurecr.io/frontend:1.1
        ports:
        - containerPort: 80

---
apiVersion: v1

kind: Service

metadata:
  name: frontend-service

spec:
  selector:
    app: teachua
    tier: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
