apiVersion: apps/v1

kind: Deployment

metadata:
  name: frontend-deployment
  labels:
    app: teachuafront

spec:
  replicas: 2
  selector:
    matchLabels:
      app: teachuafront
  template:
    metadata:
      labels:
        app: teachuafront
    spec:
      containers:
      - name: teachuafront
        image: registry646.azurecr.io/frontend:1.1
        ports:
        - containerPort: 80

---
apiVersion: v1

kind: Service

metadata:
  name: frontend-service

spec:
  selector:
    app: teachuafront
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
